#!/bin/bash
#PBS -A mccammon-hopper
#PBS -q home-hopper
#PBS -l nodes=1:ppn=8:ib
#PBS -l walltime=270:00:00
#PBS -N xp
#PBS -o pbs-${PBS_JOBID}.out
#PBS -e pbs-${PBS_JOBID}.err
#PBS -V
#

set -xv

export SCHRODINGER=/home/ux453813/pkg/schrodinger2021-1
export SCHRODINGER_TMPDIR=/oasis/tscc/scratch/cseitz/docking/mtb/no_disulfide/oxygen_channel/oxygen_437/lifechemicals/xp

cd ${PBS_O_WORKDIR}
"${SCHRODINGER}/glide" -WAIT glide-dock_xp.in -OVERWRITE -adjust -HOST localhost:8 -NJOBS 32 -NOLOCAL
