#!/bin/bash
#PBS -A mccammon-hopper
#PBS -q home-hopper
#PBS -l nodes=1:ppn=32:ib
#PBS -l walltime=270:00:00
#PBS -N htvs1
#PBS -o pbs-${PBS_JOBID}.out
#PBS -e pbs-${PBS_JOBID}.err
#PBS -V
#

set -xv

export SCHRODINGER=/home/ux453813/pkg/schrodinger2021-1
export SCHRODINGER_TMPDIR=/oasis/tscc/scratch/cseitz/docking/mtb/no_disulfide/qcpl8/cluster2/lifechemicals/sp

cd ${PBS_O_WORKDIR}
"${SCHRODINGER}/glide" -WAIT glide-dock_sp.in -OVERWRITE -adjust -HOST localhost:32 -NJOBS 128 -NOLOCAL
