#!/bin/bash
#PBS -A mccammon-hopper
#PBS -q home-hopper
#PBS -l nodes=1:ppn=4:ib
#PBS -l walltime=270:00:00
#PBS -N xp
#PBS -o pbs-${PBS_JOBID}.out
#PBS -e pbs-${PBS_JOBID}.err
#PBS -V
#

set -xv

export SCHRODINGER=/home/ux453813/pkg/schrodinger2021-1
export SCHRODINGER_TMPDIR=/oasis/tscc/scratch/cseitz/docking/ecoli/oxygen_channel/oxygen_1846/lifchemicals/xp


cd ${PBS_O_WORKDIR}
"${SCHRODINGER}/glide" -WAIT glide-dock_xp.in -OVERWRITE -adjust -HOST localhost:4 -NJOBS 16 -NOLOCAL
