#!/bin/bash
#PBS -A mccammon-hopper
#PBS -q home-hopper
#PBS -l nodes=1:ppn=36:ib
#PBS -l walltime=270:00:00
#PBS -N xp
#PBS -o pbs-${PBS_JOBID}.out
#PBS -e pbs-${PBS_JOBID}.err
#PBS -V
#

set -xv

export SCHRODINGER=/home/ux453813/pkg/schrodinger2021-1
export SCHRODINGER_TMPDIR=/oasis/tscc/scratch/cseitz/docking/mtb/disulfide/mq9/mq9_4000/lifechemicals/sp

cd ${PBS_O_WORKDIR}
"${SCHRODINGER}/glide" -WAIT glide-dock_xp.in -OVERWRITE -adjust -HOST localhost:36 -NJOBS 144 -NOLOCAL
